# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Music DH'
description:      'A Directory of Digital Scholarship in Music'
url:              'https://rutgersdh.github.io'
baseurl:          '/musicdh'
copyright:        'CC-BY 4.0 International'
logo:             'img/icon.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink:        'pretty'
sass:
    style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
  - wax_theme
  - package.json
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  musicdh: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'musicdh_item' # the layout for the pages to use
    metadata:
      source: 'musicdh.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/musicdh' # path to the directory of images within `_data`

# --------------------------------------------------------------
# LUNR SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple lunr indexes below (though only one is
# recommended!) by specifying
# a `file` to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:lunr` .
# You can optionally generate a default UI by specifying a UI file
# and running `$ bundle exec rake wax:lunr UI=true`.

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      musicdh:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - blurb
          - musicdh_genre
          - claimed_genre
          - status
          - creators
          - stewards
          - tools_used

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'Browse'
    sub:     
      - label: 'Collections & Exhibits'
        link: '/collections/'
      - label: 'Editions'
        link: '/editions/'
      - label: 'Reference Works'
        link: '/reference/'
      - label: 'Open Data'
        link: '/data/'
      - label: 'Software'
        link: '/software/'
      - label: 'Cabinet of Curiosities'
        link: '/kunstkabinett/'
  - label: 'Search'
    link: '/search/'
  - label: 'About'
    sub:
      - label: 'Call for Collaboration'
        link: '/cfc/'
      - label: 'Sources'
        link: '/reuse/'      
      - label: 'Credits'
        link: '/credits/'
      - label: 'FAQ'
        link: '/faq/'



# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/rutgersdh/musicdh'
    - label: 'Contact'
      link: 'mailto:fg162@rutgers.edu'
  logos:
    - img: '/img/mla_logo.png'
      link: 'https://www.musiclibraryassoc.org/'

# FIN
